/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslSampleUiModule extends org.xtext.example.mydsl.ui.AbstractMyDslSampleUiModule {
	public MyDslSampleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
